"""
Seed Data for SmartAP Development

Creates realistic test data:
- 10 vendors with varying risk profiles
- 20 purchase orders (open, closed, partial)
- 5 historical invoices for duplicate testing
"""

from datetime import datetime, timedelta, date
from decimal import Decimal

from ..models import (
    Vendor,
    VendorStatus,
    VendorRiskProfile,
    PaymentRecord,
    FraudFlag,
    FraudFlagType,
    PurchaseOrder,
    POLineItem,
    POStatus,
)


# Seed Vendors
SEED_VENDORS = [
    Vendor(
        vendor_id="V001",
        vendor_name="Acme Office Supplies Inc.",
        contact_name="John Smith",
        email="john.smith@acmeoffice.com",
        phone="+1-555-0101",
        address_line1="123 Business Blvd",
        city="New York",
        state="NY",
        postal_code="10001",
        country="US",
        tax_id="12-3456789",
        bank_account_number="****1234",
        bank_name="Chase Bank",
        status=VendorStatus.ACTIVE,
        payment_terms="Net 30",
        currency="USD",
        risk_profile=VendorRiskProfile(
            risk_score=0.15,
            payment_reliability_score=0.95,
            fraud_risk_score=0.0,
            total_invoices_processed=245,
            average_invoice_amount=1250.00,
            total_amount_paid=306250.00,
            last_payment_date=(date.today() - timedelta(days=5)),
        ),
        onboarded_date=(date.today() - timedelta(days=730)),
        notes="Long-term trusted vendor",
    ),
    Vendor(
        vendor_id="V002",
        vendor_name="TechGear Solutions",
        contact_name="Sarah Johnson",
        email="sarah@techgear.com",
        phone="+1-555-0202",
        address_line1="456 Tech Park Dr",
        city="San Francisco",
        state="CA",
        postal_code="94102",
        country="US",
        tax_id="98-7654321",
        bank_account_number="****5678",
        bank_name="Wells Fargo",
        status=VendorStatus.ACTIVE,
        payment_terms="Net 45",
        currency="USD",
        risk_profile=VendorRiskProfile(
            risk_score=0.25,
            payment_reliability_score=0.88,
            fraud_risk_score=0.0,
            total_invoices_processed=87,
            average_invoice_amount=3500.00,
            total_amount_paid=304500.00,
            last_payment_date=(date.today() - timedelta(days=12)),
        ),
        onboarded_date=(date.today() - timedelta(days=365)),
        notes="Medium volume vendor",
    ),
    Vendor(
        vendor_id="V003",
        vendor_name="QuickPrint Services",
        contact_name="Mike Brown",
        email="mike@quickprint.com",
        phone="+1-555-0303",
        address_line1="789 Print Lane",
        city="Chicago",
        state="IL",
        postal_code="60601",
        country="US",
        tax_id="45-1234567",
        status=VendorStatus.ACTIVE,
        payment_terms="Net 15",
        currency="USD",
        risk_profile=VendorRiskProfile(
            risk_score=0.12,
            payment_reliability_score=0.98,
            fraud_risk_score=0.0,
            total_invoices_processed=320,
            average_invoice_amount=450.00,
            total_amount_paid=144000.00,
            last_payment_date=(date.today() - timedelta(days=3)),
        ),
        onboarded_date=(date.today() - timedelta(days=1095)),
        notes="High frequency, low amount vendor",
    ),
    Vendor(
        vendor_id="V004",
        vendor_name="Global Logistics LLC",
        contact_name="Emily Davis",
        email="emily@globallogistics.com",
        phone="+1-555-0404",
        address_line1="321 Shipping Way",
        city="Houston",
        state="TX",
        postal_code="77001",
        country="US",
        tax_id="67-8901234",
        status=VendorStatus.ACTIVE,
        payment_terms="Net 60",
        currency="USD",
        risk_profile=VendorRiskProfile(
            risk_score=0.35,
            payment_reliability_score=0.82,
            fraud_risk_score=0.0,
            total_invoices_processed=42,
            average_invoice_amount=8500.00,
            total_amount_paid=357000.00,
            last_payment_date=(date.today() - timedelta(days=45)),
        ),
        onboarded_date=(date.today() - timedelta(days=180)),
        notes="New vendor, higher risk due to limited history",
    ),
    Vendor(
        vendor_id="V005",
        vendor_name="Budget Supplies Co",
        contact_name="Tom Wilson",
        email="tom@budgetsupplies.com",
        phone="+1-555-0505",
        address_line1="654 Discount Dr",
        city="Phoenix",
        state="AZ",
        postal_code="85001",
        country="US",
        tax_id="23-4567890",
        status=VendorStatus.SUSPENDED,
        payment_terms="Net 30",
        currency="USD",
        risk_profile=VendorRiskProfile(
            risk_score=0.75,
            payment_reliability_score=0.65,
            fraud_risk_score=0.6,
            total_invoices_processed=28,
            average_invoice_amount=650.00,
            total_amount_paid=18200.00,
            last_payment_date=(date.today() - timedelta(days=120)),
            active_fraud_flags=2,
            total_fraud_flags=2,
        ),
        onboarded_date=(date.today() - timedelta(days=270)),
        notes="SUSPENDED: Multiple payment issues and fraud flags",
    ),
    Vendor(
        vendor_id="V006",
        vendor_name="Premium IT Services",
        contact_name="Lisa Anderson",
        email="lisa@premiumit.com",
        phone="+1-555-0606",
        address_line1="987 Silicon Ave",
        city="Austin",
        state="TX",
        postal_code="73301",
        country="US",
        tax_id="89-0123456",
        status=VendorStatus.ACTIVE,
        payment_terms="Net 30",
        currency="USD",
        risk_profile=VendorRiskProfile(
            risk_score=0.08,
            payment_reliability_score=0.99,
            fraud_risk_score=0.0,
            total_invoices_processed=156,
            average_invoice_amount=4200.00,
            total_amount_paid=655200.00,
            last_payment_date=(date.today() - timedelta(days=7)),
        ),
        onboarded_date=(date.today() - timedelta(days=540)),
        notes="Excellent track record",
    ),
    Vendor(
        vendor_id="V007",
        vendor_name="Metro Facility Services",
        contact_name="David Garcia",
        email="david@metrofacility.com",
        phone="+1-555-0707",
        address_line1="147 Maintenance Rd",
        city="Boston",
        state="MA",
        postal_code="02101",
        country="US",
        tax_id="34-5678901",
        status=VendorStatus.ACTIVE,
        payment_terms="Net 45",
        currency="USD",
        risk_profile=VendorRiskProfile(
            risk_score=0.18,
            payment_reliability_score=0.92,
            fraud_risk_score=0.0,
            total_invoices_processed=118,
            average_invoice_amount=1850.00,
            total_amount_paid=218300.00,
            last_payment_date=(date.today() - timedelta(days=15)),
        ),
        onboarded_date=(date.today() - timedelta(days=450)),
        notes="Reliable facilities vendor",
    ),
    Vendor(
        vendor_id="V008",
        vendor_name="FastShip Express",
        contact_name="Maria Rodriguez",
        email="maria@fastship.com",
        phone="+1-555-0808",
        address_line1="258 Express Way",
        city="Miami",
        state="FL",
        postal_code="33101",
        country="US",
        tax_id="56-7890123",
        status=VendorStatus.ACTIVE,
        payment_terms="Net 15",
        currency="USD",
        risk_profile=VendorRiskProfile(
            risk_score=0.22,
            payment_reliability_score=0.89,
            fraud_risk_score=0.0,
            total_invoices_processed=203,
            average_invoice_amount=280.00,
            total_amount_paid=56840.00,
            last_payment_date=(date.today() - timedelta(days=2)),
        ),
        onboarded_date=(date.today() - timedelta(days=365)),
        notes="High frequency shipping vendor",
    ),
    Vendor(
        vendor_id="V009",
        vendor_name="New Vendor Inc",
        contact_name="Chris Taylor",
        email="chris@newvendor.com",
        phone="+1-555-0909",
        address_line1="369 Startup St",
        city="Seattle",
        state="WA",
        postal_code="98101",
        country="US",
        tax_id="78-9012345",
        status=VendorStatus.INACTIVE,  # New vendor, not yet active
        payment_terms="Net 30",
        currency="USD",
        risk_profile=VendorRiskProfile(
            risk_score=0.50,
            payment_reliability_score=0.0,
            fraud_risk_score=0.0,
            total_invoices_processed=0,
            average_invoice_amount=0.0,
            total_amount_paid=0.0,
        ),
        onboarded_date=(date.today() - timedelta(days=5)),
        notes="New vendor: Awaiting first invoice",
    ),
    Vendor(
        vendor_id="V010",
        vendor_name="Enterprise Solutions Group",
        contact_name="Robert Lee",
        email="robert@enterprisesg.com",
        phone="+1-555-1010",
        address_line1="741 Corporate Plaza",
        city="Atlanta",
        state="GA",
        postal_code="30301",
        country="US",
        tax_id="90-1234567",
        status=VendorStatus.ACTIVE,
        payment_terms="Net 60",
        currency="USD",
        risk_profile=VendorRiskProfile(
            risk_score=0.14,
            payment_reliability_score=0.94,
            fraud_risk_score=0.0,
            total_invoices_processed=68,
            average_invoice_amount=15000.00,
            total_amount_paid=1020000.00,
            last_payment_date=(date.today() - timedelta(days=18)),
        ),
        onboarded_date=(date.today() - timedelta(days=300)),
        notes="Large enterprise vendor",
    ),
]

# Map vendor IDs to names for PO seed data
VENDOR_NAMES = {
    "V001": "Acme Office Supplies Inc.",
    "V002": "TechGear Solutions",
    "V003": "QuickPrint Services",
    "V004": "ABC Consulting Group",
    "V005": "Risky Vendors LLC",
    "V006": "Reliable Hardware Corp",
    "V007": "Premium Catering Services",
    "V008": "Express Logistics Inc.",
    "V009": "New Vendor Co",
    "V010": "Enterprise Solutions Group",
}


# Seed Purchase Orders
SEED_PURCHASE_ORDERS = [
    # Open POs
    PurchaseOrder(
        po_number="PO-2025-001",
        vendor_id="V001",
        vendor_name=VENDOR_NAMES["V001"],
        created_date=(date.today() - timedelta(days=15)),
        expected_delivery=(date.today() + timedelta(days=15)),
        status=POStatus.OPEN,
        currency="USD",
        subtotal=4500.00,
        tax=360.00,
        total_amount=4860.00,
        payment_terms="Net 30",
        created_by="alice@company.com",
        line_items=[
            POLineItem(line_number=1, description="Printer Paper - 10 reams", quantity=10, unit_price=45.00, amount=450.00, sku="PP-100", unit="ream"),
            POLineItem(line_number=2, description="Stapler Set", quantity=20, unit_price=15.00, amount=300.00, sku="ST-250", unit="set"),
            POLineItem(line_number=3, description="File Folders - Box of 100", quantity=50, unit_price=12.00, amount=600.00, sku="FF-300", unit="box"),
            POLineItem(line_number=4, description="Ballpoint Pens - Pack of 12", quantity=100, unit_price=8.00, amount=800.00, sku="BP-400", unit="pack"),
            POLineItem(line_number=5, description="Desk Organizers", quantity=50, unit_price=25.00, amount=1250.00, sku="DO-500", unit="ea"),
            POLineItem(line_number=6, description="Whiteboard Markers - 4-Pack", quantity=50, unit_price=22.00, amount=1100.00, sku="WM-600", unit="pack"),
        ],
    ),
    PurchaseOrder(
        po_number="PO-2025-002",
        vendor_id="V002",
        vendor_name=VENDOR_NAMES["V002"],
        created_date=(date.today() - timedelta(days=10)),
        expected_delivery=(date.today() + timedelta(days=20)),
        status=POStatus.OPEN,
        currency="USD",
        subtotal=12000.00,
        tax=960.00,
        total_amount=12960.00,
        payment_terms="Net 45",
        created_by="bob@company.com",
        line_items=[
            POLineItem(line_number=1, description="Laptop Computer - Dell XPS 15", quantity=5, unit_price=1500.00, amount=7500.00, sku="LAP-XPS15", unit="ea"),
            POLineItem(line_number=2, description="USB-C Docking Station", quantity=5, unit_price=250.00, amount=1250.00, sku="DOCK-USBC", unit="ea"),
            POLineItem(line_number=3, description="27-inch Monitor", quantity=10, unit_price=325.00, amount=3250.00, sku="MON-27", unit="ea"),
        ],
    ),
    PurchaseOrder(
        po_number="PO-2025-003",
        vendor_id="V003",
        vendor_name=VENDOR_NAMES["V003"],
        created_date=(date.today() - timedelta(days=5)),
        expected_delivery=(date.today() + timedelta(days=10)),
        status=POStatus.OPEN,
        currency="USD",
        subtotal=1200.00,
        tax=96.00,
        total_amount=1296.00,
        payment_terms="Net 15",
        created_by="carol@company.com",
        line_items=[
            POLineItem(line_number=1, description="Business Cards - 1000 qty", quantity=10, unit_price=50.00, amount=500.00, sku="BC-1000", unit="box"),
            POLineItem(line_number=2, description="Brochures - Full Color", quantity=5, unit_price=140.00, amount=700.00, sku="BR-COLOR", unit="ream"),
        ],
    ),
    PurchaseOrder(
        po_number="PO-2025-004",
        vendor_id="V004",
        vendor_name=VENDOR_NAMES["V004"],
        created_date=(date.today() - timedelta(days=30)),
        expected_delivery=(date.today() + timedelta(days=30)),
        status=POStatus.OPEN,
        currency="USD",
        subtotal=18000.00,
        tax=1440.00,
        total_amount=19440.00,
        payment_terms="Net 60",
        created_by="dave@company.com",
        line_items=[
            POLineItem(line_number=1, description="Freight Shipping - West Coast", quantity=1, unit_price=8000.00, amount=8000.00, sku="FREIGHT-WC", unit="shipment"),
            POLineItem(line_number=2, description="Freight Shipping - East Coast", quantity=1, unit_price=10000.00, amount=10000.00, sku="FREIGHT-EC", unit="shipment"),
        ],
    ),
    # Partially Received POs
    PurchaseOrder(
        po_number="PO-2025-005",
        vendor_id="V006",
        vendor_name=VENDOR_NAMES["V006"],
        created_date=(date.today() - timedelta(days=20)),
        expected_delivery=(date.today() - timedelta(days=5)),
        status=POStatus.PARTIALLY_RECEIVED,
        currency="USD",
        subtotal=8000.00,
        tax=640.00,
        total_amount=8640.00,
        payment_terms="Net 30",
        created_by="eve@company.com",
        line_items=[
            POLineItem(line_number=1, description="Software License - Annual", quantity=20, unit_price=300.00, amount=6000.00, sku="SW-LIC-ANNUAL", unit="license", received_quantity=10.0),
            POLineItem(line_number=2, description="Technical Support - 100 hours", quantity=1, unit_price=2000.00, amount=2000.00, sku="TECH-SUPP-100", unit="package", received_quantity=0.0),
        ],
    ),
    PurchaseOrder(
        po_number="PO-2025-006",
        vendor_id="V001",
        vendor_name=VENDOR_NAMES["V001"],
        created_date=(date.today() - timedelta(days=25)),
        expected_delivery=(date.today() - timedelta(days=10)),
        status=POStatus.PARTIALLY_RECEIVED,
        currency="USD",
        subtotal=2500.00,
        tax=200.00,
        total_amount=2700.00,
        payment_terms="Net 30",
        created_by="frank@company.com",
        line_items=[
            POLineItem(line_number=1, description="Office Chairs - Ergonomic", quantity=10, unit_price=250.00, amount=2500.00, sku="CHAIR-ERG", unit="ea", received_quantity=6.0),
        ],
    ),
    # Closed/Completed POs
    PurchaseOrder(
        po_number="PO-2025-007",
        vendor_id="V003",
        vendor_name=VENDOR_NAMES["V003"],
        created_date=(date.today() - timedelta(days=40)),
        expected_delivery=(date.today() - timedelta(days=25)),
        status=POStatus.CLOSED,
        currency="USD",
        subtotal=850.00,
        tax=68.00,
        total_amount=918.00,
        payment_terms="Net 15",
        created_by="grace@company.com",
        line_items=[
            POLineItem(line_number=1, description="Marketing Flyers - 5000 qty", quantity=5, unit_price=170.00, amount=850.00, sku="FLYER-5K", unit="box", received_quantity=5.0),
        ],
    ),
    PurchaseOrder(
        po_number="PO-2025-008",
        vendor_id="V007",
        vendor_name=VENDOR_NAMES["V007"],
        created_date=(date.today() - timedelta(days=35)),
        expected_delivery=(date.today() - timedelta(days=20)),
        status=POStatus.CLOSED,
        currency="USD",
        subtotal=3500.00,
        tax=280.00,
        total_amount=3780.00,
        payment_terms="Net 45",
        created_by="henry@company.com",
        line_items=[
            POLineItem(line_number=1, description="Monthly Facility Maintenance", quantity=1, unit_price=2000.00, amount=2000.00, sku="FAC-MAINT-MONTH", unit="month", received_quantity=1.0),
            POLineItem(line_number=2, description="HVAC Service", quantity=1, unit_price=1500.00, amount=1500.00, sku="HVAC-SERVICE", unit="service", received_quantity=1.0),
        ],
    ),
    PurchaseOrder(
        po_number="PO-2024-099",
        vendor_id="V002",
        vendor_name=VENDOR_NAMES["V002"],
        created_date=(date.today() - timedelta(days=90)),
        expected_delivery=(date.today() - timedelta(days=60)),
        status=POStatus.CLOSED,
        currency="USD",
        subtotal=5000.00,
        tax=400.00,
        total_amount=5400.00,
        payment_terms="Net 45",
        created_by="iris@company.com",
        line_items=[
            POLineItem(line_number=1, description="Desktop Computers - 5 units", quantity=5, unit_price=1000.00, amount=5000.00, sku="DESK-PC", unit="ea", received_quantity=5.0),
        ],
    ),
]


# Additional POs for various scenarios
SEED_PURCHASE_ORDERS.extend([
    PurchaseOrder(
        po_number="PO-2025-009",
        vendor_id="V001",
        vendor_name=VENDOR_NAMES["V001"],
        created_date=(date.today() - timedelta(days=3)),
        expected_delivery=(date.today() + timedelta(days=27)),
        status=POStatus.OPEN,
        currency="USD",
        subtotal=850.00,
        tax=68.00,
        total_amount=918.00,
        payment_terms="Net 30",
        created_by="alice@company.com",
        line_items=[
            POLineItem(line_number=1, description="Toner Cartridges", quantity=10, unit_price=85.00, amount=850.00, sku="TONER-HP", unit="ea"),
        ],
    ),
    PurchaseOrder(
        po_number="PO-2025-010",
        vendor_id="V008",
        vendor_name=VENDOR_NAMES["V008"],
        created_date=(date.today() - timedelta(days=1)),
        expected_delivery=(date.today() + timedelta(days=14)),
        status=POStatus.OPEN,
        currency="USD",
        subtotal=750.00,
        tax=60.00,
        total_amount=810.00,
        payment_terms="Net 15",
        created_by="bob@company.com",
        line_items=[
            POLineItem(line_number=1, description="Express Shipping - 3 packages", quantity=3, unit_price=250.00, amount=750.00, sku="SHIP-EXP", unit="package"),
        ],
    ),
])


async def seed_vendors(vendor_repo):
    """Seed vendors into the database."""
    print("Seeding vendors...")
    for vendor in SEED_VENDORS:
        await vendor_repo.create(vendor)
    print(f"✓ Seeded {len(SEED_VENDORS)} vendors")


async def seed_purchase_orders(po_repo):
    """Seed purchase orders into the database."""
    print("Seeding purchase orders...")
    for po in SEED_PURCHASE_ORDERS:
        await po_repo.create(po)
    print(f"✓ Seeded {len(SEED_PURCHASE_ORDERS)} purchase orders")


async def run_seed(session):
    """Run all seed operations."""
    from .repositories import VendorRepository, PurchaseOrderRepository
    
    vendor_repo = VendorRepository(session)
    po_repo = PurchaseOrderRepository(session)
    
    await seed_vendors(vendor_repo)
    await seed_purchase_orders(po_repo)
    
    await session.commit()
    print("\n✓ Database seeding complete!")

